name: Publish Packages
on:
  workflow_dispatch:
    inputs:
      commit-lint:
        type: boolean
        default: true
        description: Publish commit-lint
      validation-messages:
        type: boolean
        default: true
        description: Publish validation-messages
      linking-tool:
        type: boolean
        default: false
        description: Publish linking-tool
      typed-urls:
        type: boolean
        default: false
        description: Publish typed-urls
  push: null
jobs:
  publish_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@house-of-angular'
        env:
          NODE_AUTH_TOKEN: test
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Set up input variables
        run: |
          echo "COMMIT_LINT=true" >> $GITHUB_ENV
          echo "VALIDATION_MESSAGES=true" >> $GITHUB_ENV
          echo "TYPED_URLS=true" >> $GITHUB_ENV
          echo "LINKING_TOOL=false" >> $GITHUB_ENV
      - name: Publish packages
        run: |
          packages=("commit-lint" "typed-urls" "validation-messages" "linking-tool")
          inputs=($COMMIT_LINT $TYPED_URLS $VALIDATION_MESSAGES $LINKING_TOOL)
          counter=0
          for package in "${packages[@]}"; do
            if [[ "${inputs[$counter]}" = "true" ]]; then
              echo "Publishing $package..."
              cd ./dist/projects/$package
              cd ../../..
            fi
            ((counter++))
          done
